In [ ]:
# 1.Write a function to compute 5/0 and use try/except to catch the exceptions.

In [3]:
def dividbyzero():
    res=0.0
    try:
        res=5/0
    except:
        print('Devide By Zero Error -You trying to divide by Zero ')
    else:
        print(res)

In [4]:
dividbyzero()

Devide By Zero Error -You trying to divide by Zero 


In [5]:
# 2. Implement a Python program to generate all sentences where subject is in ["Americans",
# "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

#Output should come as below:

#Americans play Baseball.
#Americans play Cricket.
#Americans watch Baseball.
#Americans watch Cricket.
#Indians play Baseball.
#Indians play Cricket.
#Indians watch Baseball.
#Indians watch Cricket.

In [6]:
def gensent():
    subject=['Americans','Indians']
    verb=['Play','watch']
    obj=['Baseball','cricket']
    for i in range(len(subject)):
        for j in range(len(subject)):
            for k in range(len(subject)):
                print(subject[i]+' '+verb[j]+' '+obj[k])

In [7]:
gensent()

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [8]:
# Task 2. Write a function so that the columns of the output matrix are powers of the input vector.

In [9]:
import numpy as np

In [124]:
def althvan(X,N=None):
    lst=list()
    mt=np.zeros((N,N))
    if N is None:
        N=len(X)
    for i in range(N-1,-1,-1):
        for j in range(len(X)):
            lst.append(X[j]**i)
        col=np.array(lst)[np.newaxis]
        col2=col.T
    k=0
    for i in range(len(mt)):
        for j in range(N):
            if(k<len(lst)):
                mt[j][i]=lst[k]
            k=k+1
                
                
    print(mt)
    
    
    

In [125]:
althvan([1,2,3,5],4)
#lst1=[1,2,3,4]
#c=np.array(lst1)[np.newaxis]
#c=c.T
#c

[[  1.   1.   1.   1.]
 [  8.   4.   2.   1.]
 [ 27.   9.   3.   1.]
 [125.  25.   5.   1.]]
